### ISSUE TITLE
MissingPluginException while trying to get all UPI apps

### ISSUE THREAD

**Issue by reeteshranjan** [mdazharuddin1011999/UPI-Plugin-Flutter#19] opened 2020-09-17 10:32 UTC
```
E/flutter ( 7357): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method getAllUpiApps on channel com.az.upi_india)
E/flutter ( 7357): #0 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:7)
E/flutter ( 7357):
E/flutter ( 7357): #1 MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
E/flutter ( 7357): #2 MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:347:40)
E/flutter ( 7357): #3 UpiIndia.getAllUpiApps (package:upi_india/upi_india.dart:23:24)
```
Android Version 6

Is there any other Kotlin/Java/AndroidManifest.xml configuration/modification required other than including the package?

**Comment by azhar1038** [comment] 2020-09-17 14:55
Package is written in java. If you are using Kotlin, it still doesn't matter because flutter can handle it. Are you sure it's not a duplicate of #15 ?

**Closed as completed** 2020-09-17 19:52 UTC

**Comment by azhar1038** [comment] 2020-09-27 05:00
Were you able to overcome this problem?

**Comment by reeteshranjan** [comment] 2020-09-27 05:28
Yes

**Comment by azhar1038** [comment] 2020-09-27 05:30
Okay!

**Comment by ShahnazABH** [comment] 2020-10-21 10:53
> Yes
> […](#)
> On 27-Sep-2020, at 10:31 AM, Md.Azharuddin ***@***.***> wrote: ﻿ Were you able to overcome this problem? — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

how??i am facing the same issue.Pls help

**Comment by azhar1038** [comment] 2020-10-21 10:57
Rebuild the app. Just hot restart or reload won't work.
Check this flutter/flutter#10912 ?

**Comment by ShahnazABH** [comment] 2020-10-21 11:02
> Rebuild the app. Just hot restart or reload won't work.
> Check this [flutter/flutter#10912](https://github.com/flutter/flutter/issues/10912) ?

yes..i tried this..but still showing the same.I used upi_india: ^2.2.0. Is the version correct?

**Comment by azhar1038** [comment] 2020-10-21 11:05
Have you tried flutter clean?

**Comment by ShahnazABH** [comment] 2020-10-21 11:13
> Have you tried flutter clean?

Tried once again. But still the same.

**Comment by azhar1038** [comment] 2020-10-21 11:16
What's your flutter version? Which android version you are using?

Have you tried other things mentioned at flutter/flutter#10912 ?

**Comment by ShahnazABH** [comment] 2020-10-21 11:20
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.6 19G73, locale en-US)
    • Flutter version 1.22.2 at /Users/Pramodk/Desktop/development/flutter
    • Framework revision 84f3d28555 (6 days ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/Pramodk/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

 
[✓] Connected device (1 available)            
   

• No issues found!

**Comment by azhar1038** [comment] 2020-10-21 11:22
Are you by any chance compiling it for iOS?

**Comment by ShahnazABH** [comment] 2020-10-21 11:31
for android

**Comment by azhar1038** [comment] 2020-10-21 11:41
Was it working with older version of plugin?

Can you share your logs?

**Comment by ShahnazABH** [comment] 2020-10-21 12:13
Thank you...now it works..

> What's your flutter version? Which android version you are using?
> 
> Have you tried other things mentioned at [flutter/flutter#10912](https://github.com/flutter/flutter/issues/10912) ?

**Comment by ShahnazABH** [comment] 2020-10-21 13:57
when is UpiPaymentStatus.SUBMITTED returned? will the cash be debited from user? Can we expect the transaction to be successful and subsequently proceed with the placing of order? @mdazharuddin1011999

**Comment by azhar1038** [comment] 2020-10-21 14:04
A pending payment is supposed to return SUBMITTED. A pending request may fail or succeed later. If it fails money will be refunded.

**Comment by ShahnazABH** [comment] 2020-10-21 14:29
ok...so in case it returns UpiPaymentStatus.SUBMITTED, will there be a transactionId returned in UpiResponse for further reference?

**Comment by azhar1038** [comment] 2020-10-21 14:35
It should return transaction id but I have never encountered a pending status.
